Angga branch
rdnuansa/homework-sesi14 pull request #6
Opened 2023-01-11 10:16 UTC by anggastika

penambahan konten angga

2023-01-11 13:53 UTC, rdnuansa requested changes

2023-01-11 13:53 UTC, rdnuansa commented on commit_dari_Anggastika/angga.txt
> +belajar lagi 2
Nice mas Angga. Coba file text ini diubah jadi semacam readme file, dalam format [markdown syntax](https://www.markdownguide.org/basic-syntax/).

2023-01-25 14:26 UTC, anggastika commented on commit_dari_Anggastika/angga.txt
> +belajar lagi 2
done mas @rdnuansa

2023-02-02 07:07 UTC, rdnuansa approved these changes

2023-02-16 08:13 UTC, merged